### ISSUE TITLE
Not in F-Droid store?

### ISSUE THREAD

**Issue by NeroRome** [SecUSo/privacy-friendly-solitaire#17]
I can't find this application in the F-Droid store.

I see there have been two releases for fdroid (https://github.com/SecUSo/privacy-friendly-solitaire/releases/tag/v1.0.1 and https://github.com/SecUSo/privacy-friendly-solitaire/releases/tag/v1.0.2 [2 days ago]), but it's not there.
https://search.f-droid.org/?q=solitaire&lang=en and https://search.f-droid.org/?q=pfa&page=1&lang=de doesn't report this app. It's also not available by browsing the store.

**Comment by Kamuno** [comment]
It is currently in the process of being included.
See here: https://gitlab.com/fdroid/rfp/issues/781
