### ISSUE TITLE
App closes when pressing New game

### ISSUE THREAD

**Issue by jsarkari** [SecUSo/privacy-friendly-solitaire#30]
Just inatalled on Samsung Galaxy S22 Ultra using Android 13 OneUI 5.1 but unable to play the game.

I tested turn off all the options in setting but still when pressing the button "NEW GAME" it crashes out.

I also tested different performance modes I have from performance t
![Screenshot_20231010_070532_Device care](https://github.com/SecUSo/privacy-friendly-solitaire/assets/18397011/7f12cb0b-9105-482b-8e17-e6a55068b338)
o standard then got a message when it crashed out.

But tested all the other option in the menu and everything works apart from changing colour, after selecting a new colour everthing remains as the default colour.

**Comment by thomas2403** [comment]
Same here, Oneplus 8T, LineageOS 19 (Android12)

**Comment by mjssRN** [comment]
Just inatalled on Samsung Galaxy A23 using Android 13. But unable to play the game.

**Comment by darrencoen** [comment]
Android 11, moto 5g ace -- same issue, crashes on new game button.

**Comment by camouflage81** [comment]
Same issue with Google Pixel 7a Android 14

**Comment by jsarkari** [comment]
However works fine on Sailfish os

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by CyberMinion** [comment]
Same here on Android 14. 
It was working a month ago, but both the app and the OS have updated since then.

**Comment by jsarkari** [comment]
I no longer have the mobile so unable to retest.
